apiVersion: v1
kind: Service
metadata:
  name: krakend
  namespace: es1-platform
  labels:
    app: krakend
    app.kubernetes.io/name: krakend
    app.kubernetes.io/part-of: es1-platform
spec:
  type: ClusterIP
  selector:
    app: krakend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: metrics
      port: 8090
      targetPort: 8090
      protocol: TCP
