---
apiVersion: v1
kind: Namespace
metadata:
  name: engine-platform
  labels:
    app.kubernetes.io/part-of: engine-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: engine-infrastructure
  labels:
    app.kubernetes.io/part-of: engine-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: engine-monitoring
  labels:
    app.kubernetes.io/part-of: engine-platform
